import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Deputado from './src/telas/telaDeputado'
import Home from './src/telas/telaDeputados/index'
import GraficoGastos from './src/telas/telaGraficoGastos'

const inter = Inter({ subsets: ['latin'] })

//<Deputado Cpf={'99770962104'} Foto={'https://www.camara.leg.br/internet/deputado/bandep/220593.jpg'} NomeDeputado={'Abilio Brunini'} Sexo={'M'} Uf={'MT'} Sigla={'PL'} fk_Partido_id={11} id={220593}/>

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"bg-slate-200 text-gray-900"}><GraficoGastos/></body>
    </html>
  )
}
