import Header from '@/pages/components/Header'
import Home from '@/pages/telas'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

//<Deputado Cpf={'99770962104'} Foto={'https://www.camara.leg.br/internet/deputado/bandep/220593.jpg'} NomeDeputado={'Abilio Brunini'} Sexo={'M'} Uf={'MT'} Sigla={'PL'} fk_Partido_id={11} id={220593}/>

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header/>
      <Home/>
    </html>
  )
}
